export default {
  id: 'cricket',
  name: 'Cricket',
  emoji: '🏏',
  accent: '#06d6a0',
  spice: 2,
  description: 'Gully to the world stage.',
  questions: [
    { tier: 1, q: "How many players from one side are on the field in cricket?",
      options: ['11', '10', '9', '12'], answer: 0 },
    { tier: 1, q: "Which nation won the inaugural 2007 ICC T20 World Cup?",
      options: ['India', 'Pakistan', 'Australia', 'England'], answer: 0 },
    { tier: 2, q: "Who is the highest run-scorer in international cricket history?",
      options: ['Sachin Tendulkar', 'Ricky Ponting', 'Kumar Sangakkara', 'Virat Kohli'], answer: 0 },
    { tier: 2, q: "What do you call three wickets taken on three consecutive deliveries?",
      options: ['Hat-trick', 'Maiden', 'Golden duck', 'Yorker'], answer: 0 },
    { tier: 3, q: "Who hit the winning six in the 2011 ODI World Cup final?",
      options: ['MS Dhoni', 'Yuvraj Singh', 'Gautam Gambhir', 'Virat Kohli'], answer: 0 },
    { tier: 4, q: "Who scored the first double century in men's ODI cricket?",
      options: ['Sachin Tendulkar', 'Rohit Sharma', 'Virender Sehwag', 'Chris Gayle'], answer: 0 },
    { tier: 5, q: "Who holds the record for the highest individual score in Test cricket (400*)?",
      options: ['Brian Lara', 'Don Bradman', 'Matthew Hayden', 'Virender Sehwag'], answer: 0 },
  ],
};
