export default {
  id: 'hollywood',
  name: 'Hollywood',
  emoji: '🤠',
  accent: '#4cc9f0',
  spice: 1,
  description: 'The Western blockbuster canon.',
  questions: [
    { tier: 1, q: "Which sci-fi saga features the line “May the Force be with you”?",
      options: ['Star Wars', 'Star Trek', 'Dune', 'Guardians of the Galaxy'], answer: 0 },
    { tier: 1, q: "Who directed “Jurassic Park” (1993)?",
      options: ['Steven Spielberg', 'James Cameron', 'Ridley Scott', 'George Lucas'], answer: 0 },
    { tier: 2, q: "In “The Matrix”, which pill does Neo take to learn the truth?",
      options: ['Red', 'Blue', 'Green', 'Yellow'], answer: 0 },
    { tier: 2, q: "Which studio made “Toy Story” (1995)?",
      options: ['Pixar', 'DreamWorks', 'Studio Ghibli', 'Illumination'], answer: 0 },
    { tier: 3, q: "Which 1972 film features “an offer he can't refuse”?",
      options: ['The Godfather', 'Goodfellas', 'Scarface', 'Casino'], answer: 0 },
    { tier: 4, q: "Who composed the scores for Jaws, Star Wars, and Indiana Jones?",
      options: ['John Williams', 'Hans Zimmer', 'Ennio Morricone', 'Danny Elfman'], answer: 0 },
    { tier: 5, q: "Which film won the very first Academy Award for Best Picture (1929)?",
      options: ['Wings', 'Sunrise', 'The Jazz Singer', 'Metropolis'], answer: 0 },
  ],
};
